[2024-10-28T20:27:16.711+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-28T20:27:16.728+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tab_social_media.daily_instagram_stats manual__2024-10-28T18:17:02.510729+00:00 [queued]>
[2024-10-28T20:27:16.733+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tab_social_media.daily_instagram_stats manual__2024-10-28T18:17:02.510729+00:00 [queued]>
[2024-10-28T20:27:16.734+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 4
[2024-10-28T20:27:16.744+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): daily_instagram_stats> on 2024-10-28 18:17:02.510729+00:00
[2024-10-28T20:27:16.756+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2964) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-28T20:27:16.757+0000] {standard_task_runner.py:72} INFO - Started process 2977 to run task
[2024-10-28T20:27:16.758+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tab_social_media', 'daily_instagram_stats', 'manual__2024-10-28T18:17:02.510729+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/tab_social_media.py', '--cfg-path', '/tmp/tmp5gb28tg1']
[2024-10-28T20:27:16.760+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask daily_instagram_stats
[2024-10-28T20:27:16.798+0000] {task_command.py:467} INFO - Running <TaskInstance: tab_social_media.daily_instagram_stats manual__2024-10-28T18:17:02.510729+00:00 [running]> on host 7f9c284dabe4
[2024-10-28T20:27:16.866+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel.cristancho' AIRFLOW_CTX_DAG_ID='tab_social_media' AIRFLOW_CTX_TASK_ID='daily_instagram_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T18:17:02.510729+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T18:17:02.510729+00:00'
[2024-10-28T20:27:16.867+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-28T20:27:18.594+0000] {evolution_stats_instagram.py:35} INFO - Start extract loaded data
[2024-10-28T20:27:22.311+0000] {evolution_stats_instagram.py:38} INFO - Start load new data
[2024-10-28T20:27:22.311+0000] {evolution_stats_instagram.py:108} INFO - writing user_follow_stats table
[2024-10-28T20:27:24.555+0000] {evolution_stats_instagram.py:112} INFO - 3 rows load in user_follow_stats
[2024-10-28T20:27:24.556+0000] {evolution_stats_instagram.py:113} INFO - loading operation finished successfully for user_follow_stats
[2024-10-28T20:27:24.556+0000] {logging_mixin.py:190} INFO - ****************** Success process to update instagram post
[2024-10-28T20:27:24.557+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-28T20:27:24.567+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-28T20:27:24.568+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tab_social_media, task_id=daily_instagram_stats, run_id=manual__2024-10-28T18:17:02.510729+00:00, execution_date=20241028T181702, start_date=20241028T202716, end_date=20241028T202724
[2024-10-28T20:27:24.597+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-28T20:27:24.622+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-28T20:27:24.623+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
